version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Navigate to backend directory"
      - cd backend
      - echo "Install dependencies"
      - yarn install
  build:
    commands:
      - echo "Build the application"
      - yarn run build
  post_build:
    commands:
      - echo "Running tests"
      - yarn test
      - echo "Copy necessary files to the dist directory"
      - cp Procfile dist/
      - cp package.json dist/
      - cp yarn.lock dist/
      - echo "Packaging the application for Elastic Beanstalk"
      - cd dist
      - zip -r ../my-app.zip .
artifacts:
  files:
    - my-app.zip
  discard-paths: yes
  base-directory: backend