version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Navigate to backend directory"
      - cd backend
      - echo "Install dependencies"
      - yarn install
  build:
    commands:
      - echo "Build the application"
      - yarn run build
  post_build:
    commands:
      - echo "Running tests"
      - yarn test
artifacts:
  files:
    - '**/*'
  base-directory: 'backend'
  discard-paths: yes