version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Navigate to backend directory"
      - cd backend
      - echo "Install dependencies"
      - yarn install
  build:
    commands:
      - echo "Build the application"
      - yarn run build
  post_build:
    commands:
      - echo "Running tests"
      - yarn test
      - echo "Packaging the application for Elastic Beanstalk"
      - cp package.json ./dist
      - cp yarn.lock ./dist
      - cp Procfile ./dist
      - echo "Creating ZIP file"
      - cd dist
      - zip -r build.zip .
      - ls

artifacts:
  files:
    - '**/*.zip'
  discard-paths: yes